name = "tourism-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Staging environment
[env.staging]
name = "tourism-api-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "tourism-db-staging"
database_id = "a8e8c149-e3d1-4d0c-97ec-b5d8032a7c38"

# Production environment
[env.production]
name = "tourism-api-production"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "tourism-db-production"
database_id = "a2473118-a81d-497a-9040-5c378a7ae432"

