-- Migration from Google Sheets to Cloudflare D1
-- Generated: 2025-10-23T18:57:52.090Z
-- 
-- Usage: 
--   wrangler d1 execute tourism-db --file=migrations/0002_data_import.sql
-- 

-- Insert client: FunTrip Tours in Jamaica
INSERT INTO clients (slug, name, email, status) VALUES ('funtrip-tours', 'FunTrip Tours in Jamaica', 'info@funtriptoursinjamaica.com', 'active');

-- Tour 1: Blue Hole Secret Falls Adventure
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'blue-hole-secret-falls-adventure',
  'Blue Hole Secret Falls Adventure',
  'Discover one of Jamaica’s most breathtaking natural wonders.',
  '<p>Discover one of Jamaica’s most breathtaking natural wonders. The Blue Hole offers turquoise pools, hidden caves, and rope swings for a day of refreshing adventure surrounded by lush tropical forest.</p><h4>Includes</h4><ul><li>Private transportation</li><li>entry fees</li><li>licensed tour guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/676c0e72540e17fceb5fb329.jpeg',
  '[]',
  'Ocho Rios, Jamaica',
  'Adventure',
  '4–5 hours',
  270,
  135,
  '["Adventure seekers","Couples","Nature lovers"]',
  '[]',
  '["Private transportation","entry fees","licensed tour guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Ocho Rios\"","\"Adventure\"]"]',
  'active'
);

-- Tour 2: Dunn’s River Falls Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'dunns-river-falls-tour',
  'Dunn’s River Falls Tour',
  'Climb the world-famous Dunn’s River Falls, one of Jamaica’s must-see attractions.',
  '<p>Climb the world-famous Dunn’s River Falls, one of Jamaica’s must-see attractions. Enjoy the thrill of scaling cascading limestone steps while surrounded by calm, rushing water and tropical beauty.</p><h4>Includes</h4><ul><li>Private transportation</li><li>entry fees</li><li>licensed guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/676c0e727a5c4c3ee1688b97.png',
  '[]',
  'Ocho Rios, Jamaica',
  'Adventure',
  '4–5 hours',
  270,
  125,
  '["Families","Groups","Cruise ship visitors"]',
  '[]',
  '["Private transportation","entry fees","licensed guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Ocho Rios\"","\"Adventure\"]"]',
  'active'
);

-- Tour 3: Dunn’s River Falls & Blue Hole Combo
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'dunns-river-falls-blue-hole-combo',
  'Dunn’s River Falls & Blue Hole Combo',
  'Double the adventure with this two-in-one excursion.',
  '<p>Double the adventure with this two-in-one excursion. Experience the excitement of climbing Dunn’s River Falls, then dive into the natural pools and waterfalls of the Blue Hole for a refreshing finish.</p><h4>Includes</h4><ul><li>Private transportation</li><li>entry fees</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/6861da144044f876a8066e84.jpeg',
  '[]',
  'Ocho Rios, Jamaica',
  'Adventure',
  '6–7 hours',
  390,
  179,
  '["Active travelers","Families","Couples"]',
  '[]',
  '["Private transportation","entry fees","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Ocho Rios\"","\"Adventure\"]"]',
  'active'
);

-- Tour 4: Dunn’s River Falls, Blue Hole & Horseback Riding
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'dunns-river-falls-blue-hole-horseback-riding',
  'Dunn’s River Falls, Blue Hole & Horseback Riding',
  'Enjoy a full day of adventure combining two of Jamaica’s top waterfalls with a scenic horseback ride and ocean swim.',
  '<p>Enjoy a full day of adventure combining two of Jamaica’s top waterfalls with a scenic horseback ride and ocean swim. It’s a perfect blend of excitement, nature, and cultural charm.</p><h4>Includes</h4><ul><li>Transportation</li><li>entry fees</li><li>horseback riding equipment</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/685b0c33b6ee7afd031121b0.jpeg',
  '[]',
  'Ocho Rios, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  199,
  '["Adventure lovers","Couples","Groups"]',
  '[]',
  '["Transportation","entry fees","horseback riding equipment","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Ocho Rios\"","\"Adventure\"]"]',
  'active'
);

-- Tour 5: Island River Tubing Adventure
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'island-river-tubing-adventure',
  'Island River Tubing Adventure',
  'Float downstream on gentle currents through Jamaica’s lush rainforest.',
  '<p>Float downstream on gentle currents through Jamaica’s lush rainforest. This river tubing experience offers peaceful moments and light rapids for an unforgettable nature escape.</p><h4>Includes</h4><ul><li>Equipment</li><li>guide</li><li>transportation</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Ocho Rios or Montego Bay, Jamaica',
  'Adventure',
  '3–4 hours',
  210,
  135,
  '["Families","Couples","Relaxation seekers"]',
  '[]',
  '["Equipment","guide","transportation","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Ocho Rios or Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 6: ATV - Dune buggy Outback Jungle Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'atv-dune-buggy-outback-jungle-tour',
  'ATV - Dune buggy Outback Jungle Tour',
  'Venture deep into Jamaica’s rugged countryside.',
  '<p>Venture deep into Jamaica’s rugged countryside. Explore scenic trails, hidden waterfalls, and authentic rural culture while connecting with nature in a thrilling off-the-beaten-path adventure.</p><h4>Includes</h4><ul><li>Transportation</li><li>local guide</li><li>entry fees</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/676c0e722ec4eb71ff4c358e.jpeg',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  165,
  '["Adventure seekers","Explorers","Nature lovers"]',
  '[]',
  '["Transportation","local guide","entry fees","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 7: Y.S. Falls River Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'y-s-falls-river-tour',
  'Y.S. Falls River Tour',
  'Visit one of Jamaica’s most picturesque natural attractions.',
  '<p>Visit one of Jamaica’s most picturesque natural attractions. Y.S. Falls features cascading tiers, natural pools, and lush gardens — the ideal setting for relaxation and exploration.</p><h4>Includes</h4><ul><li>Entry fees</li><li>private transportation</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'South Coast, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  135,
  '["Families","Nature enthusiasts","Photographers"]',
  '[]',
  '["Entry fees","private transportation","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"South Coast\"","\"Adventure\"]"]',
  'active'
);

-- Tour 8: Mayfield Falls Rainforest Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'mayfield-falls-rainforest-experience',
  'Mayfield Falls Rainforest Experience',
  'Immerse yourself in Jamaica’s rainforest at Mayfield Falls.',
  '<p>Immerse yourself in Jamaica’s rainforest at Mayfield Falls. Enjoy a refreshing swim under natural waterfalls, walk through tropical vegetation, and experience true serenity.</p><h4>Includes</h4><ul><li>Entry fees</li><li>transportation</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Hanover, Jamaica',
  'Adventure',
  '5–6 hours',
  330,
  149,
  '["Couples","Nature lovers","Wellness travelers"]',
  '[]',
  '["Entry fees","transportation","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Hanover\"","\"Adventure\"]"]',
  'active'
);

-- Tour 9: Horseback Riding & Swim Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'horseback-riding-swim-experience',
  'Horseback Riding & Swim Experience',
  'Ride through scenic countryside trails and along the shoreline before entering the Caribbean Sea for a refreshing swim on horseback.',
  '<p>Ride through scenic countryside trails and along the shoreline before entering the Caribbean Sea for a refreshing swim on horseback. A truly unforgettable Jamaican adventure that blends relaxation and excitement.</p><h4>Includes</h4><ul><li>Entry fees</li><li>safety gear</li><li>professional guide</li><li>transportation</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/685b0c33b6ee7afd031121b0.jpeg',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  '3–4 hours',
  210,
  99,
  '["Couples","First-time riders","Families"]',
  '[]',
  '["Entry fees","safety gear","professional guide","transportation","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 10: Bamboo Rafting with Limestone Foot Massage
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'bamboo-rafting-with-limestone-foot-massage',
  'Bamboo Rafting with Limestone Foot Massage',
  'Drift peacefully down the Lethe River aboard a handcrafted bamboo raft.',
  '<p>Drift peacefully down the Lethe River aboard a handcrafted bamboo raft. Enjoy a rejuvenating limestone foot massage from your raft captain as you glide through tranquil tropical scenery.</p><h4>Includes</h4><ul><li>Private transportation</li><li>raft captain</li><li>limestone foot massage</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/676c0e72f58cbd50ffefbfcf.jpeg',
  '[]',
  'Lethe, Montego Bay, Jamaica',
  'Adventure',
  '3–4 hours',
  210,
  125,
  '["Couples","Relaxation seekers","Culture lovers"]',
  '[]',
  '["Private transportation","raft captain","limestone foot massage","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Lethe\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 11: Bamboo Rafting & Beach Day Combo
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'bamboo-rafting-beach-day-combo',
  'Bamboo Rafting & Beach Day Combo',
  'Start your morning floating along the serene Lethe River, then unwind with an afternoon on one of Jamaica’s beautiful beaches—a perfect balance of relaxation and sunshine.',
  '<p>Start your morning floating along the serene Lethe River, then unwind with an afternoon on one of Jamaica’s beautiful beaches—a perfect balance of relaxation and sunshine.</p><h4>Includes</h4><ul><li>Transportation</li><li>limestone foot massage</li><li>beach access</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/676c0e72f58cbdc323efbfd0.jpeg',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  '5–6 hours',
  330,
  149,
  '["Couples","Wellness travelers","Friends’ getaways"]',
  '[]',
  '["Transportation","limestone foot massage","beach access","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 12: Montego Bay Catamaran / Party Boat Cruise
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'montego-bay-catamaran-party-boat-cruise',
  'Montego Bay Catamaran / Party Boat Cruise',
  'Sail along Montego Bay’s coastline on a lively catamaran! Enjoy tropical music, snorkeling stops, and a party atmosphere with drinks and sunshine.',
  '<p>Sail along Montego Bay’s coastline on a lively catamaran! Enjoy tropical music, snorkeling stops, and a party atmosphere with drinks and sunshine.</p><h4>Includes</h4><ul><li>Cruise</li><li>open bar</li><li>snorkeling equipment</li><li>music</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  '3–4 hours',
  210,
  149,
  '["Groups","Friends","Celebration seekers"]',
  '[]',
  '["Cruise","open bar","snorkeling equipment","music","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 13: Negril Rick’s Café Catamaran & Beach Day Sunset Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'negril-ricks-cafe-catamaran-beach-day-sunset-tour',
  'Negril Rick’s Café Catamaran & Beach Day Sunset Tour',
  'Spend a day in paradise sailing along Negril’s famous Seven Mile Beach.',
  '<p>Spend a day in paradise sailing along Negril’s famous Seven Mile Beach. Snorkel in clear waters, enjoy beach time, and end your day at Rick’s Café watching Jamaica’s most stunning sunset.</p><h4>Includes</h4><ul><li>Transportation</li><li>catamaran cruise</li><li>snorkeling</li><li>entry to Rick’s Café</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Negril, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  159,
  '["Couples","Groups","Adventure seekers"]',
  '[]',
  '["Transportation","catamaran cruise","snorkeling","entry to Rick’s Café","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Negril\"","\"Adventure\"]"]',
  'active'
);

-- Tour 14: Negril 7-Mile Beach & Sunset at Rick’s Café
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'negril-7-mile-beach-sunset-at-ricks-cafe',
  'Negril 7-Mile Beach & Sunset at Rick’s Café',
  'Relax on the world-famous Seven Mile Beach and cap off your day with drinks and live entertainment at Rick’s Café as the sun dips below the horizon.',
  '<p>Relax on the world-famous Seven Mile Beach and cap off your day with drinks and live entertainment at Rick’s Café as the sun dips below the horizon.</p><h4>Includes</h4><ul><li>Transportation</li><li>beach access</li><li>entry to Rick’s Café</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Negril, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  125,
  '["Beach lovers","Couples","Friends"]',
  '[]',
  '["Transportation","beach access","entry to Rick’s Café","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Negril\"","\"Adventure\"]"]',
  'active'
);

-- Tour 15: Dunn’s River & Catamaran Cruise Combo
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'dunns-river-catamaran-cruise-combo',
  'Dunn’s River & Catamaran Cruise Combo',
  'Combine Jamaica’s most iconic waterfall with a fun-filled catamaran cruise.',
  '<p>Combine Jamaica’s most iconic waterfall with a fun-filled catamaran cruise. Climb the falls, then relax onboard with music, snorkeling, and open-bar vibes.</p><h4>Includes</h4><ul><li>Transportation</li><li>catamaran cruise</li><li>entry to Dunn’s River Falls</li><li>snorkeling</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Ocho Rios, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  179,
  '["Adventure lovers","Groups","Families"]',
  '[]',
  '["Transportation","catamaran cruise","entry to Dunn’s River Falls","snorkeling","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Ocho Rios\"","\"Adventure\"]"]',
  'active'
);

-- Tour 16: Jetcar on Water Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'jetcar-on-water-experience',
  'Jetcar on Water Experience',
  'Drive a high-powered jetcar across the Caribbean Sea! Experience adrenaline, speed, and style in this one-of-a-kind aquatic thrill ride.',
  '<p>Drive a high-powered jetcar across the Caribbean Sea! Experience adrenaline, speed, and style in this one-of-a-kind aquatic thrill ride.</p><h4>Includes</h4><ul><li>Safety gear</li><li>jetcar rental</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  '2–3 hours (15 minutes on the water in Jetcar)',
  150,
  299,
  '["Thrill seekers","Couples","Adventure enthusiasts"]',
  '[]',
  '["Safety gear","jetcar rental","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 17: Deep Sea Fishing
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'deep-sea-fishing',
  'Deep Sea Fishing',
  'Sail into Jamaica’s deep blue waters and try your luck catching mahi-mahi, tuna, or marlin.',
  '<p>Sail into Jamaica’s deep blue waters and try your luck catching mahi-mahi, tuna, or marlin. Perfect for anglers and sea lovers alike.</p><h4>Includes</h4><ul><li>Boat charter</li><li>fishing gear</li><li>crew</li><li>refreshments</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  '4–5 hours',
  270,
  250,
  '["Fishing enthusiasts","Groups","Families"]',
  '[]',
  '["Boat charter","fishing gear","crew","refreshments","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 18: Deep Sea “Catch & Eat” Fishing Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'deep-sea-catch-eat-fishing-experience',
  'Deep Sea “Catch & Eat” Fishing Experience',
  'Reel in your own catch and enjoy it cooked fresh the Jamaican way.',
  '<p>Reel in your own catch and enjoy it cooked fresh the Jamaican way. This exclusive “Catch & Eat” adventure combines excitement on the sea with delicious island flavors.</p><h4>Includes</h4><ul><li>Boat charter</li><li>fishing gear</li><li>crew</li><li>meal preparation of your catch</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Adventure',
  'Full Day (6–8 hours)',
  420,
  350,
  '["Foodies","Fishing lovers","Groups"]',
  '[]',
  '["Boat charter","fishing gear","crew","meal preparation of your catch","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Adventure\"]"]',
  'active'
);

-- Tour 19: Wellness Vegan Eco Retreat
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'wellness-vegan-eco-retreat',
  'Wellness Vegan Eco Retreat',
  'Rejuvenate your body and spirit at a serene vegan retreat surrounded by nature.',
  '<p>Rejuvenate your body and spirit at a serene vegan retreat surrounded by nature. Enjoy yoga, healthy cuisine, and authentic Jamaican hospitality.</p><h4>Includes</h4><ul><li>Transportation</li><li>plant-based meals</li><li>eco-tours</li><li>wellness activities</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay or Negril, Jamaica',
  'Culture, Wellness & Lifestyle',
  'Full Day (6–8 hours)',
  420,
  149,
  '["Wellness travelers","Vegans","Couples"]',
  '[]',
  '["Transportation","plant-based meals","eco-tours","wellness activities","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay or Negril\"","\"Culture","Wellness & Lifestyle\"]"]',
  'active'
);

-- Tour 20: Cannabis & Vegan Cultural Vibration Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'cannabis-vegan-cultural-vibration-tour',
  'Cannabis & Vegan Cultural Vibration Tour',
  'Discover Jamaica’s rich herbal traditions and Rastafarian culture through this immersive tour blending wellness, plant-based dining, and local music.',
  '<p>Discover Jamaica’s rich herbal traditions and Rastafarian culture through this immersive tour blending wellness, plant-based dining, and local music.</p><h4>Includes</h4><ul><li>Transportation</li><li>guided tour</li><li>vegan lunch</li><li>cannabis education</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Culture, Wellness & Lifestyle',
  'Full Day (6–8 hours)',
  420,
  249,
  '["Culture enthusiasts","Wellness travelers","Curious explorers"]',
  '[]',
  '["Transportation","guided tour","vegan lunch","cannabis education","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Culture","Wellness & Lifestyle\"]"]',
  'active'
);

-- Tour 21: Appleton Estate Rum Tasting Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'appleton-estate-rum-tasting-experience',
  'Appleton Estate Rum Tasting Experience',
  'Journey to the world-famous Appleton Estate for an insider look at Jamaica’s oldest rum distillery.',
  '<p>Journey to the world-famous Appleton Estate for an insider look at Jamaica’s oldest rum distillery. Learn the craft of rum making and sample premium blends.</p><h4>Includes</h4><ul><li>Transportation</li><li>entry fees</li><li>guided distillery tour</li><li>rum tastings</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'South Coast, Jamaica',
  'Culture, Wellness & Lifestyle',
  'Full Day (6–8 hours)',
  420,
  149,
  '["Spirit enthusiasts","Couples","Groups"]',
  '[]',
  '["Transportation","entry fees","guided distillery tour","rum tastings","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"South Coast\"","\"Culture","Wellness & Lifestyle\"]"]',
  'active'
);

-- Tour 22: Black River Safari & Pelican Bar Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'black-river-safari-pelican-bar-experience',
  'Black River Safari & Pelican Bar Experience',
  'Explore Jamaica’s longest river on a scenic safari where you’ll spot crocodiles and native birds, then unwind at the iconic Pelican Bar built on stilts in the middle of the sea.',
  '<p>Explore Jamaica’s longest river on a scenic safari where you’ll spot crocodiles and native birds, then unwind at the iconic Pelican Bar built on stilts in the middle of the sea.</p><h4>Includes</h4><ul><li>Transportation</li><li>safari river cruise</li><li>Pelican Bar stop</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'South Coast, Jamaica',
  'Culture, Wellness & Lifestyle',
  'Full Day (6–8 hours)',
  420,
  179,
  '["Nature lovers","Couples","Photographers"]',
  '[]',
  '["Transportation","safari river cruise","Pelican Bar stop","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"South Coast\"","\"Culture","Wellness & Lifestyle\"]"]',
  'active'
);

-- Tour 23: Fine Wine & Fine Food Culinary Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'fine-wine-fine-food-culinary-tour',
  'Fine Wine & Fine Food Culinary Tour',
  'Indulge in an elegant culinary journey through Jamaica’s finest dining spots.',
  '<p>Indulge in an elegant culinary journey through Jamaica’s finest dining spots. Savor island-inspired dishes paired with world-class wines for an unforgettable experience.</p><h4>Includes</h4><ul><li>Transportation</li><li>gourmet dining experience</li><li>wine tasting</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Culture, Wellness & Lifestyle',
  '5–6 hours',
  330,
  199,
  '["Foodies","Couples","Special occasions"]',
  '[]',
  '["Transportation","gourmet dining experience","wine tasting","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Culture","Wellness & Lifestyle\"]"]',
  'active'
);

-- Tour 24: Luminous Lagoon Night Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'luminous-lagoon-night-tour',
  'Luminous Lagoon Night Tour',
  'Witness the magical glow of the Luminous Lagoon, where microorganisms light up the water with every movement.',
  '<p>Witness the magical glow of the Luminous Lagoon, where microorganisms light up the water with every movement. A breathtaking natural wonder you’ll never forget.</p><h4>Includes</h4><ul><li>Transportation</li><li>boat ride</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/685b15f94bfc6131068112f2.jpeg',
  '[]',
  'Falmouth, Jamaica',
  'Nightlife & Entertainment',
  '2–3 hours',
  150,
  79,
  '["Couples","Families","Nighttime explorers"]',
  '[]',
  '["Transportation","boat ride","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Falmouth\"","\"Nightlife & Entertainment\"]"]',
  'active'
);

-- Tour 25: Luminous Lagoon & Rose Hall Great House Combo
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'luminous-lagoon-rose-hall-great-house-combo',
  'Luminous Lagoon & Rose Hall Great House Combo',
  'Combine two of Jamaica’s top evening attractions — the glowing Luminous Lagoon and the historic Rose Hall Great House.',
  '<p>Combine two of Jamaica’s top evening attractions — the glowing Luminous Lagoon and the historic Rose Hall Great House. Perfect for travelers seeking mystery and beauty.</p><h4>Includes</h4><ul><li>Transportation</li><li>entry fees</li><li>guided tours</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  'https://storage.googleapis.com/msgsndr/EuRPlvfvsApARJSERsbj/media/685b16231aca00c1f550b9a0.jpeg',
  '[]',
  'Falmouth & Montego Bay, Jamaica',
  'Nightlife & Entertainment',
  '4–5 hours',
  270,
  125,
  '["Couples","History lovers","Adventurers"]',
  '[]',
  '["Transportation","entry fees","guided tours","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Falmouth & Montego Bay\"","\"Nightlife & Entertainment\"]"]',
  'active'
);

-- Tour 26: Montego Bay Street Food Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'montego-bay-street-food-tour',
  'Montego Bay Street Food Tour',
  'Taste Jamaica’s authentic street cuisine, from jerk chicken to pepper shrimp.',
  '<p>Taste Jamaica’s authentic street cuisine, from jerk chicken to pepper shrimp. This flavorful tour offers a delicious glimpse into island life.</p><h4>Includes</h4><ul><li>Transportation</li><li>local guide</li><li>food samples</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Nightlife & Entertainment',
  '3–4 hours',
  210,
  99,
  '["Food lovers","Culture explorers","Groups"]',
  '[]',
  '["Transportation","local guide","food samples","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Nightlife & Entertainment\"]"]',
  'active'
);

-- Tour 27: Montego Bay Nightclub Crawl
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'montego-bay-nightclub-crawl',
  'Montego Bay Nightclub Crawl',
  'Dance the night away as you hop between Montego Bay’s hottest nightclubs.',
  '<p>Dance the night away as you hop between Montego Bay’s hottest nightclubs. Enjoy music, drinks, and a vibrant atmosphere that only Jamaica can deliver.</p><h4>Includes</h4><ul><li>Transportation</li><li>club entries</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Nightlife & Entertainment',
  '4–5 hours',
  270,
  99,
  '["Friends","Party seekers","Nightlife enthusiasts"]',
  '[]',
  '["Transportation","club entries","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Nightlife & Entertainment\"]"]',
  'active'
);

-- Tour 28: Montego Bay Party Boat Cruise into the Club
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'montego-bay-party-boat-cruise-into-the-club',
  'Montego Bay Party Boat Cruise into the Club',
  'Start your evening with a fun-filled party boat cruise, then continue the night at one of Montego Bay’s top clubs—the ultimate day-to-night experience.',
  '<p>Start your evening with a fun-filled party boat cruise, then continue the night at one of Montego Bay’s top clubs—the ultimate day-to-night experience.</p><h4>Includes</h4><ul><li>Party boat cruise</li><li>open bar</li><li>club entry</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay, Jamaica',
  'Nightlife & Entertainment',
  '5–6 hours',
  330,
  149,
  '["Groups","Couples","Celebrations"]',
  '[]',
  '["Party boat cruise","open bar","club entry","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Montego Bay\"","\"Nightlife & Entertainment\"]"]',
  'active'
);

-- Tour 29: Negril Sea Life Experience
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'negril-sea-life-experience',
  'Negril Sea Life Experience',
  'Explore Negril’s underwater paradise and witness vibrant marine life up close.',
  '<p>Explore Negril’s underwater paradise and witness vibrant marine life up close. Perfect for snorkeling fans and ocean adventurers.</p><h4>Includes</h4><ul><li>Snorkeling gear</li><li>transportation</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Negril, Jamaica',
  'Negril & West End Experiences',
  '4–5 hours',
  270,
  149,
  '["Families","Snorkelers","Nature lovers"]',
  '[]',
  '["Snorkeling gear","transportation","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Negril\"","\"Negril & West End Experiences\"]"]',
  'active'
);

-- Tour 30: Negril Blue Hole Mineral Spring
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'negril-blue-hole-mineral-spring',
  'Negril Blue Hole Mineral Spring',
  'Jump or swim into the natural mineral spring tucked away in the Negril cliffs.',
  '<p>Jump or swim into the natural mineral spring tucked away in the Negril cliffs. The therapeutic waters and rustic charm make this a local favorite.</p><h4>Includes</h4><ul><li>Transportation</li><li>entry fees</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Negril, Jamaica',
  'Negril & West End Experiences',
  '4–5 hours',
  270,
  159,
  '["Adventure seekers","Couples","Groups"]',
  '[]',
  '["Transportation","entry fees","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Negril\"","\"Negril & West End Experiences\"]"]',
  'active'
);

-- Tour 31: Negril Cannabis & Weed Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'negril-cannabis-weed-tour',
  'Negril Cannabis & Weed Tour',
  'Discover Jamaica’s cannabis culture firsthand.',
  '<p>Discover Jamaica’s cannabis culture firsthand. Visit local farms, meet growers, and learn about the island’s herbal heritage.</p><h4>Includes</h4><ul><li>Transportation</li><li>guided farm visit</li><li>cultural tour</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Negril, Jamaica',
  'Negril & West End Experiences',
  '5–6 hours',
  330,
  159,
  '["Culture enthusiasts","Groups","Curious travelers"]',
  '[]',
  '["Transportation","guided farm visit","cultural tour","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Negril\"","\"Negril & West End Experiences\"]"]',
  'active'
);

-- Tour 32: Kingston Airport Transfer to Montego Bay Hotels
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'kingston-airport-transfer-to-montego-bay-hotels',
  'Kingston Airport Transfer to Montego Bay Hotels',
  'Enjoy a comfortable and safe transfer from Kingston Airport to Montego Bay hotels.',
  '<p>Enjoy a comfortable and safe transfer from Kingston Airport to Montego Bay hotels. Relax and let our professional drivers take care of everything.</p><h4>Includes</h4><ul><li>Private air-conditioned vehicle</li><li>driver</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Kingston to Montego Bay, Jamaica',
  'Transfers & Specialty Add-Ons',
  '3–4 hours (depending on traffic)',
  210,
  125,
  '["Travelers","Couples","Families"]',
  '[]',
  '["Private air-conditioned vehicle","driver","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["[\"Jamaica\"","\"Kingston to Montego Bay\"","\"Transfers & Specialty Add-Ons\"]"]',
  'active'
);

-- Tour 33: Golfing Island Style
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'funtrip-tours'),
  'golfing-island-style',
  'Golfing Island Style',
  'Play a round at one of Jamaica’s scenic golf courses surrounded by tropical landscapes and ocean breezes.',
  '<p>Play a round at one of Jamaica’s scenic golf courses surrounded by tropical landscapes and ocean breezes.</p><h4>Includes</h4><ul><li>Transportation</li><li>golf course access</li><li>guide</li><li>complimentary cold Red Stripe beer</li><li>bottled water</li></ul>',
  '',
  '[]',
  'Montego Bay or Ocho Rios, Jamaica',
  'Transfers & Specialty Add-Ons',
  '4–5 hours',
  270,
  125,
  '["Golf lovers","Couples","Friends"]',
  '[]',
  '["Transportation","golf course access","guide","complimentary cold Red Stripe beer","bottled water"]',
  '[]',
  '[]',
  '["Jamaica","Montego Bay or Ocho Rios","Transfers & Specialty Add-Ons"]',
  'active'
);

-- Insert client: Kamar Tours Jamaica
INSERT INTO clients (slug, name, email, status) VALUES ('kamar-tours', 'Kamar Tours Jamaica', 'info@kamartoursjamaica.com', 'active');

-- Tour 1: Dunn’s River Falls Tour
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'kamar-tours'),
  'dunns-river-falls',
  'Dunn’s River Falls Tour',
  'Discover the majestic beauty of Dunn’s River Falls with shopping and sightseeing in one seamless Kamar Tours experience.',
  '<p>Our tour to Dunn’s River Falls in Ocho Rios is a must‑do adventure that showcases the island’s breathtaking natural beauty. Join hands with fellow adventurers as you ascend the 600‑foot cascading falls, feel the refreshing waters, and take in stunning views at the top. Designed for most ages and fitness levels. <strong>Product code: DRF</strong>.</p>',
  'https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428ffcf3f5b2f8ca161.jpeg',
  '["https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428ffcf3f9f168ca160.jpeg"]',
  'Ocho Rios, Jamaica',
  'River',
  '2 - 3 Hours (approx.)',
  240,
  60,
  '["Guided climb up the falls","Scenic viewpoints and photo stops","Option for shopping & sightseeing","Round‑trip transportation"]',
  '["Hotel/cruise pickup","Drive to Ocho Rios","Guided climb at Dunn’s River Falls","Sightseeing & shopping stop (time permitting)","Return transfer"]',
  '["Round‑trip transportation","Professional guide"]',
  '["Food & drinks","Gratuities","Entrance fees (confirm if included)"]',
  '[{"q":"Is the climb suitable for beginners?","a":"Yes. Guides assist you and there are rest points along the way."},{"q":"What should I bring?","a":"Water shoes, towel, swimsuit, and sunscreen."}]',
  '["dunns river falls","waterfall","ocho rios","family-friendly","nature"]',
  'active'
);

-- Tour 2: Blue Hole in Ocho Rios
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'kamar-tours'),
  'blue-hole-ocho-rios',
  'Blue Hole in Ocho Rios',
  'Swim, climb, and (optionally) cliff‑jump at Ocho Rios’ famous Blue Hole—plus sightseeing & shopping.',
  '<p>The Blue Hole tour combines adventure and culture: swim in crystal‑clear pools, explore waterfalls, enjoy Ocho Rios sightseeing, and browse local shops. Includes entrance fees and round‑trip transportation. <strong>Product code: BH</strong>.</p>',
  'https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d4286c057a7f68c5eb82.jpeg',
  '["https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d4288c9269c82caffb59.jpeg"]',
  'Ocho Rios, Jamaica',
  'River',
  '2 - 3 Hours (approx.)',
  240,
  65,
  '["Natural pools & waterfalls","Optional cliff jumps","Sightseeing & shopping","Round‑trip transportation"]',
  '["Pickup from hotel/cruise","Guided Blue Hole experience","Sightseeing around Ocho Rios","Shopping stop at local markets","Return transfer"]',
  '["Entrance fees","Round‑trip transportation","Bottled water","Hotel/cruise pickup & drop‑off"]',
  '["Food & snacks","Gratuities"]',
  '[{"q":"Do I have to cliff jump?","a":"No—cliff jumping is optional. You can swim and explore at your own comfort level."},{"q":"Is the tour family‑friendly?","a":"Yes, guides assist beginners and life vests are available on request."}]',
  '["blue hole","waterfall","ocho rios","swimming","shopping"]',
  'active'
);

-- Tour 3: ATV Adventure
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'kamar-tours'),
  'atv-adventure',
  'ATV Adventure',
  'Ride through rugged off‑road trails, rivers, and lush countryside—then add sightseeing & shopping in Ocho Rios.',
  '<p>The ATV Adventure takes you deep into Jamaica’s hills for an exhilarating off‑road ride. Helmets and gear provided; suitable for thrill‑seekers and nature lovers. Includes hotel pickup/drop‑off. <strong>Product code: ATV</strong>.</p>',
  'https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d4286c057aaa22c5eb81.jpeg',
  '["https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428ccdd18ee77f6dd7e.jpeg"]',
  'Ocho Rios, Jamaica',
  'River',
  '2 - 3 Hours (approx.)',
  240,
  195,
  '["Guided off‑road ATV ride","River splashes & scenic trails","Safety briefing & gear provided","Sightseeing & shopping add‑on"]',
  '["Pickup & safety briefing","Guided ATV ride on country trails","Photo/viewpoint stops","Shopping stop (time permitting)","Return transfer"]',
  '["Round‑trip transportation","ATV, helmet & safety gear","Professional guide"]',
  '["Food & drinks","Gratuities","Photos/video"]',
  '[{"q":"Do I need prior ATV experience?","a":"No. Basic instruction is provided; guides set a comfortable pace."},{"q":"What should I wear?","a":"Closed‑toe shoes and clothes you don’t mind getting dusty or muddy."}]',
  '["atv","adventure","ocho rios","off-road"]',
  'active'
);

-- Tour 4: Horseback Ride & Swim (Ocho Rios)
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'kamar-tours'),
  'horseback-ride-swim-ocho-rios',
  'Horseback Ride & Swim (Ocho Rios)',
  'Scenic horseback ride through tropical trails followed by a unique swim on horseback in the Caribbean Sea.',
  '<p>Enjoy a peaceful countryside ride that leads to the shoreline, then experience the unforgettable swim on horseback. Afterwards, relax at Bamboo Blu Beach. Includes transport and safety gear. <strong>Product code: HRS</strong>.</p>',
  'https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d4286c057a6b75c5eb83.jpeg',
  '["https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428c994908672324f63.jpeg"]',
  'Ocho Rios, Jamaica',
  'Beach',
  '2 - 3 Hours (approx.)',
  240,
  95,
  '["Guided beachside trail ride","Swim on horseback","Helmets & safety briefing","Relax time at Bamboo Blu Beach"]',
  '["Pickup from hotel/cruise","Trail ride through countryside","Swim on horseback at the beach","Relax at Bamboo Blu Beach","Return transfer"]',
  '["Round‑trip transportation","Helmets & safety briefing","Professional guides"]',
  '["Food & drinks","Beach facility fees (if any)","Gratuities"]',
  '[{"q":"Is it suitable for beginners?","a":"Yes. Guides match horses to rider ability and provide instructions."},{"q":"Weight or age limits?","a":"Limits may apply—please confirm at booking time."}]',
  '["horseback","beach","ocho rios","bamboo blu"]',
  'active'
);

-- Tour 5: Bamboo Rafting on the White River
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'kamar-tours'),
  'bamboo-rafting-on-the-white-river',
  'Bamboo Rafting on the White River',
  'A gentle, romantic bamboo‑raft glide on the White River—with optional shopping and scenic Fern Gully drive.',
  '<p>Glide peacefully down the White River on a traditional bamboo raft steered by an experienced captain. A tranquil, romantic experience with optional shopping and scenic detours. <strong>Product code: BR</strong>.</p>',
  'https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428270a3be5d95d8b42.jpeg',
  '["https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428c99490d901324f64.jpeg"]',
  'Ocho Rios, Jamaica',
  'River',
  '2 Hours (approx.)',
  120,
  150,
  '["Handcrafted bamboo raft","Lush rainforest scenery","Optional swim stop","Cultural insights from your captain"]',
  '["Pickup from hotel/cruise","Bamboo raft ride on White River","Optional swim/photo stop","Optional shopping or Fern Gully drive","Return transfer"]',
  '["Round‑trip transportation","Raft with experienced captain"]',
  '["Food & drinks","Souvenirs","Gratuities"]',
  '[{"q":"Is this suitable for non‑swimmers?","a":"Yes. The ride is gentle; life vests available on request."},{"q":"Can couples share a raft?","a":"Yes—availability depends on weight limits and raft capacity."}]',
  '["bamboo rafting","white river","ocho rios","couples","relaxation"]',
  'active'
);

-- Tour 6: Snorkeling at Coral Reef (Ocho Rios)
INSERT INTO tours (
  client_id,
  slug,
  name,
  excerpt,
  description_html,
  image,
  gallery,
  location,
  type,
  duration,
  duration_minutes,
  from_price,
  highlights,
  itinerary,
  inclusions,
  exclusions,
  faqs,
  tags,
  status
) VALUES (
  (SELECT id FROM clients WHERE slug = 'kamar-tours'),
  'snorkeling-at-coral-reef-ocho-rios',
  'Snorkeling at Coral Reef (Ocho Rios)',
  'Guided reef snorkel with gear included—see tropical fish, vibrant corals, and marine life up close.',
  '<p>Explore one of Ocho Rios’ best coral reefs with all gear included. See schools of tropical fish and colorful corals on an easy guided snorkel. <strong>Product code: SCR</strong>.</p>',
  'https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d428ffcf3f97238ca15f.jpeg',
  '["https://storage.googleapis.com/msgsndr/ztielRaZD8er3UEUZBUg/media/68e3d420c994901d0f324ea0.jpeg"]',
  'Ocho Rios, Jamaica',
  'Beach',
  '2 Hours (approx.)',
  120,
  90,
  '["All snorkeling gear provided","Professional guide assistance","Calm reef suitable for beginners","Optional shopping & sightseeing"]',
  '["Pickup from hotel/cruise","Boat transfer & safety briefing","Guided snorkel on coral reef","Optional shopping/sightseeing stop","Return transfer"]',
  '["Round‑trip transportation","Snorkel, mask, fins, life jacket","Bottled water"]',
  '["Food & drinks","GoPro/photos (optional add‑on)","Gratuities"]',
  '[{"q":"Can beginners join?","a":"Yes—guides assist non‑swimmers and flotation is available."},{"q":"What should I bring?","a":"Swimsuit, towel, reef‑safe sunscreen."}]',
  '["snorkeling","coral reef","ocho rios","marine life","family-friendly"]',
  'active'
);

